[package]
name = "execute_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rbpf = {git = "https://github.com/dymchenkko/rbpf", rev = "e9274de5d6391c641bf996e23660024e73c1902f"}
